### ISSUE TITLE
Error while serializing NBT after /give player AIR

### ISSUE THREAD

**Issue by dequis** [GlowstoneMC/Glowstone-Legacy#104]
```
01:33:54 [INFO] dequis issued command: /give dequis 0
01:33:54 [INFO] dequis: Gave dequis some 0 (AIR)
01:33:57 [INFO] dequis issued command: /give dequis 1
01:33:57 [INFO] dequis: Gave dequis some 1 (STONE)
01:33:59 [INFO] dequis [/127.0.0.1:60585] lost connection
01:33:59 [SEVERE] Error while executing GlowTask{id=14, plugin=null, sync=false: net.glowstone.entity.GlowPlayer$2@79521e90}
java.lang.IllegalArgumentException: Item meta null was not created by GlowItemFactory
        at net.glowstone.inventory.GlowItemFactory.toGlowMeta(GlowItemFactory.java:81)
        at net.glowstone.inventory.GlowItemFactory.writeNbt(GlowItemFactory.java:52)
        at net.glowstone.io.nbt.NbtSerialization.writeItem(NbtSerialization.java:42)
        at net.glowstone.io.nbt.NbtSerialization.writeInventory(NbtSerialization.java:65)
        at net.glowstone.io.entity.HumanEntityStore.save(HumanEntityStore.java:42)
        at net.glowstone.io.entity.PlayerStore.save(PlayerStore.java:53)
        at net.glowstone.io.entity.PlayerStore.save(PlayerStore.java:10)
        at net.glowstone.io.nbt.NbtWorldMetadataService.writePlayerData(NbtWorldMetadataService.java:217)
        at net.glowstone.entity.GlowPlayer$2.run(GlowPlayer.java:986)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at net.glowstone.scheduler.GlowTask.run(GlowTask.java:163)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
```

The stone (or any of the items given later) didn't appear in the player inventory in the minecraft UI, but the error didn't appear until I disconnected it

**Comment by turt2live** [comment]
Cannot reproduce on latest master

**Comment by turt2live** [comment]
I have a bad habit already of eager closing :(

Anyways, reproduced the issue of disappearing items, but not the error.

**Comment by turt2live** [comment]
Just noting what I noted on the pull request associated with this ticket: I can no longer reproduce any issues relating to adding air to my inventory on the current master branch. @dequis please confirm you have no issues alongside the already mentioned people on the pull request. Thanks!

**Comment by turt2live** [comment]
Confirmed by other parties that this is no longer an issue. If the issue persists, please comment here or open a new ticket, thanks!
