### ISSUE TITLE
CME in GlowPlayer#streamBlocks()

### ISSUE THREAD

**Issue by SpaceManiac** [GlowstoneMC/Glowstone-Legacy#127]
```
14:39:02 [SEVERE] Error occurred while pulsing world world
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:926)
        at java.util.HashMap$KeyIterator.next(HashMap.java:960)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:341)
        at java.util.HashSet.<init>(HashSet.java:117)
        at net.glowstone.entity.GlowPlayer.streamBlocks(GlowPlayer.java:453)
        at net.glowstone.entity.GlowPlayer.pulse(GlowPlayer.java:359)
        at net.glowstone.GlowWorld.pulse(GlowWorld.java:362)
        at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:48)
```

**Comment by turt2live** [comment]
@SpaceManiac reproduction information? (I doubt there's much :( )
