### ISSUE TITLE
AIOOBE in getSlotType (with full log)

### ISSUE THREAD

**Issue by LB--** [GlowstoneMC/Glowstone-Legacy#128]
I did some experimenting.
https://gist.github.com/LB--/1e662b88f8c2c58dcebe
I could never get past the crazy inventory mechanics. Most of those exceptions were when I was clicking on legitimate inventory slots. Also there's duplication with the 2x2 crafting window.

**Comment by navarr** [comment]
For the developer's ease, it's the same exception over and over again

```
java.lang.ArrayIndexOutOfBoundsException: -999
    at net.glowstone.inventory.GlowInventory.getSlotType(GlowInventory.java:99)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.process(WindowClickHandler.java:47)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:23)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:19)
    at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:82)
    at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:141)
    at net.glowstone.net.GlowSession.pulse(GlowSession.java:368)
    at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:172)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:109)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

prefaced by something like

`2014/08/17 22:57:31 [SEVERE] Error while handling WindowClickMessage{id=0, slot=-999, button=0, transaction=10, mode=5, item=null} (handler: WindowClickHandler)`

**Comment by ewized** [comment]
I would love that its debugging right in the error

**Comment by SpaceManiac** [comment]
Would you mind giving the [`inventory` branch](https://github.com/SpaceManiac/Glowstone/tree/inventory) a shake? It fixes this specific exception and should provide more robust inventory handling than before (though it's still lacking in a few areas, these should be fairly well logged).

Here's a ~~[download](http://wombat.platymuus.com/dl/glowstone-inventory.jar)~~ if you're not in the mood to compile it yourself.

**Comment by LB--** [comment]
it's a bit better, I only get the exception when clicking outside the inventory window now, but there is definitely still some issues for sure - different items have different success rates for crafting them. I have crafted wood, sticks, and a crafting table, but still no sign yet. I have a short 5-minute video of my attempts: https://www.youtube.com/watch?v=SFNl2hQywFo and the server log: https://gist.github.com/LB--/4fac624f5512214a73a6

I still notice some randomness to it as well - normally with clicking items I would not get debug messages, but then randomly one of the items I would place down (even between two "good" places) would send a debug message. I've noticed the debug message seems to only appear when I perform a click it thinks does nothing.

Also, dragging seems to not be implemented, but the client likes to start and end drags in the same slot if you accidentally move your mouse while clicking, so that made things hard.

**Comment by SpaceManiac** [comment]
~~[New build](http://wombat.platymuus.com/dl/glowstone-inventory.jar)~~ with some more fixes (changes on branch). Specifically, drag and collect-to-cursor actions should work, and so should the sign recipe (and other recipes which would have broken before). No-ops appearing to be failures has also been fixed. Notably still missing are: deducting items when you craft (allows infinite crafting currently), full shift-click support, prevention of putting items into weird places, and items dropping in all cases (currently they are lost, added back to the inventory, or dropped depending on the circumstances). The debugging messages have also been improved somewhat. This should lead to significantly less craziness.

Thanks a bunch for the help with testing.

**Comment by LB--** [comment]
Definitely working much better! Found one last issue:

``` plain
2014/08/19 18:51:32 [INFO] LB725C: [rejected] WindowClickMessage{id=0, slot=0, button=0, transaction=36, mode=0, item=ItemStack{WOOD x 4}}
2014/08/19 18:51:33 [SEVERE] Error while handling WindowClickMessage{id=0, slot=-999, button=2, transaction=39, mode=5, item=null} (handler: WindowClickHandler)
java.lang.NullPointerException
    at net.glowstone.net.handler.play.inv.WindowClickHandler.process(WindowClickHandler.java:96)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:31)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:27)
    at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:82)
    at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:141)
    at net.glowstone.net.GlowSession.pulse(GlowSession.java:368)
    at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:172)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:109)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

I placed wood in my 2x2 crafting window and crafted the planks, closed and reopened the inventory, the recipe had returned and the messages came when I took the result again and placed it in my inventory again.

**Comment by SpaceManiac** [comment]
The important fixes and improvements have been merged into master for about a week. There's certainly work to be done on inventory but I'm considering this issue closed. Feel free to file another if you hit anything else.
