### ISSUE TITLE
World loading problems

### ISSUE THREAD

**Issue by SpaceManiac** [GlowstoneMC/Glowstone-Legacy#135]
Discovered on [Spigot forums](http://www.spigotmc.org/threads/glowstone-platform-discussion.27418/#post-306942). Running on 926872a.
Simplified log:

```
Error loading TileEntity (MOB_SPAWNER)...
    IllegalArgumentException: Compound does not contain IntTag "Delay"
    at TEMobSpawner.loadNbt (line 24)
Error loading entity...
    Unknown entity type to load: "Chicken"
    at AnvilChunkIoService.read (line 100)
Error while loading chunk...
    IllegalArgumentException: List "TileEntities" contains BYTE, not COMPOUND
    at AnvilChunkIoService.read (line 110)
```

First two errors are caught and logged by chunk read and do not cause chunk corruption. First error could be fixed. Second error is just unimplemented feature. Last one is problematic and likely a problem with `CompoundTag#getTagList` not being as polite as could be about empty lists.

Original log:
![Error log](http://puu.sh/b4dE4/ce15739e14.png)

**Comment by SpaceManiac** [comment]
Fresh trace from ColdFyre on IRC:

```
16:45:37 [SEVERE] Error loading TileEntity at GlowBlock{chunk=GlowChunk{world=castiana,x=-59,z=23},x=-939,y=43,z=368,type=MOB_SPAWNER,data=0}
java.lang.IllegalArgumentException: Compound does not contain IntTag "Delay"
        at net.glowstone.util.nbt.CompoundTag.getTag(CompoundTag.java:265)
        at net.glowstone.util.nbt.CompoundTag.get(CompoundTag.java:259)
        at net.glowstone.util.nbt.CompoundTag.getInt(CompoundTag.java:75)
        at net.glowstone.block.entity.TEMobSpawner.loadNbt(TEMobSpawner.java:24)
        at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:118)
        at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:120)
        at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:189)
        at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:221)
        at net.glowstone.entity.GlowPlayer.streamBlocks(GlowPlayer.java:506)
        at net.glowstone.entity.GlowPlayer.pulse(GlowPlayer.java:368)
        at net.glowstone.GlowWorld.pulse(GlowWorld.java:362)
        at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:48)
16:45:37 [SEVERE] Error while loading chunk (-58,23)
java.lang.IllegalArgumentException: List "TileEntities" contains BYTE, not COMPOUND
        at net.glowstone.util.nbt.CompoundTag.getTagList(CompoundTag.java:278)
        at net.glowstone.util.nbt.CompoundTag.getCompoundList(CompoundTag.java:120)
        at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:110)
        at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:120)
        at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:189)
        at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:221)
        at net.glowstone.entity.GlowPlayer.streamBlocks(GlowPlayer.java:506)
        at net.glowstone.entity.GlowPlayer.pulse(GlowPlayer.java:368)
        at net.glowstone.GlowWorld.pulse(GlowWorld.java:362)
```

**Comment by laurentdu51** [comment]
Hello, i'm have the error in import à bukkit world via multivers 2.5.

http://pastebin.com/zLtpNWfB

**Comment by laurentdu51** [comment]
Hello, i'm have test with the build #58 and have not the sam error but i'm have another error on loading world.

http://pastebin.com/dwASvYG2
