### ISSUE TITLE
Error while loading chunk on first run

### ISSUE THREAD

**Issue by SpaceManiac** [GlowstoneMC/Glowstone-Legacy#136]
``` irc
<kookster> first run
<kookster> i opped myself
<kookster> then i set my gamemode to creative
<kookster> started flying
```

Presumably the chunk shouldn't have even been written yet, so it's odd to see an error loading it.

```
18:59:16 [INFO] This server is running Glowstone version 1.8-1-g40d9363-b46 (Imp
lementing API version 1.7.9-R0.1)
18:59:16 [INFO] Created default config: config\glowstone.yml
18:59:17 [INFO] Recipes: 259 shaped, 58 shapeless, 22 furnace, 15 fuels.
18:59:17 [INFO] Preparing spawn for world...
18:59:18 [INFO] Preparing spawn for world: 14%
18:59:19 [INFO] Preparing spawn for world: 33%
18:59:20 [INFO] Preparing spawn for world: 48%
18:59:21 [INFO] Preparing spawn for world: 66%
18:59:22 [INFO] Preparing spawn for world: 84%
18:59:23 [INFO] Preparing spawn for world: done
18:59:23 [INFO] Preparing spawn for world_nether...
18:59:24 [INFO] Preparing spawn for world_nether: 28%
18:59:25 [INFO] Preparing spawn for world_nether: 63%
18:59:26 [INFO] Preparing spawn for world_nether: 95%
18:59:26 [INFO] Preparing spawn for world_nether: done
18:59:26 [INFO] Preparing spawn for world_the_end...
18:59:27 [INFO] Preparing spawn for world_the_end: 43%
18:59:28 [INFO] Preparing spawn for world_the_end: 91%
18:59:28 [INFO] Preparing spawn for world_the_end: done
18:59:28 [INFO] Created default config: config\commands.yml
18:59:28 [INFO] Created default config: config\permissions.yml
18:59:28 [INFO] Binding to address: 0.0.0.0/0.0.0.0:25565...
18:59:29 [INFO] Ready for connections.
19:01:10 [INFO] [/192.168.1.119:55020] kicked: Outdated client!
19:02:26 [INFO] [/192.168.1.119:55082] kicked: Outdated client!
19:03:25 [INFO] kookster [/192.168.1.119:55142] connected, UUID: 273758c0-820b-4e75-bc72-92addaa1db2e
19:03:25 [INFO] kookster joined the game
19:03:26 [INFO] kookster: ClientSettingsMessage{locale='en_US', viewDistance=12, chatFlags=0, chatColors=true, skinFlags=127}
19:03:26 [INFO] Client brand of kookster is: vanilla
19:03:31 [INFO] kookster issued command: /gamemode 1
>op kookster
19:03:34 [INFO] CONSOLE: Opped kookster
19:03:42 [INFO] kookster issued command: /gamemode 1
19:03:42 [INFO] kookster: Set own game mode to CREATIVE mode
19:04:34 [SEVERE] Error while loading chunk (42,22)
java.io.IOException: Invalid length
        at net.glowstone.io.anvil.RegionFile.getChunkDataInputStream(RegionFile.java:200)
        at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:66)
        at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:120)
        at net.glowstone.ChunkManager.populateChunk(ChunkManager.java:189)
        at net.glowstone.ChunkManager.forcePopulation(ChunkManager.java:220)
        at net.glowstone.entity.GlowPlayer.streamBlocks(GlowPlayer.java:507)
        at net.glowstone.entity.GlowPlayer.pulse(GlowPlayer.java:367)
        at net.glowstone.GlowWorld.pulse(GlowWorld.java:362)
        at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:48)
```

**Comment by SkeletonGamer** [comment]
I have got the same bug but with [GRAVE] flag. It happened when I was walking towards the horizon.

09:35:58 [GRAVE] Error while loading chunk (25,-17)
java.io.IOException: Invalid length
    at net.glowstone.io.anvil.RegionFile.getChunkDataInputStream(RegionFile.java:200)
    at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:66)
    at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:120)
    at net.glowstone.GlowChunk.load(GlowChunk.java:287)
    at net.glowstone.GlowChunk.load(GlowChunk.java:283)
    at net.glowstone.GlowChunk.toMessage(GlowChunk.java:607)
    at net.glowstone.GlowChunk.toMessage(GlowChunk.java:598)
    at net.glowstone.entity.GlowPlayer.streamBlocks(GlowPlayer.java:520)
    at net.glowstone.entity.GlowPlayer.pulse(GlowPlayer.java:368)
    at net.glowstone.GlowWorld.pulse(GlowWorld.java:362)
    at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:48)

**Comment by turt2live** [comment]
Any possible information on this? World files?

**Comment by SkeletonGamer** [comment]
The world was created with default Glowstone generator.
