### ISSUE TITLE
EncryptionKeyResponseHandler error on connection cancel

### ISSUE THREAD

**Issue by SpaceManiac** [GlowstoneMC/Glowstone-Legacy#154]
Clicked 'cancel' while logging in, produced this error (trying to manipulate pipeline of closed connection?):

```
15:35:33 [SEVERE] Error while handling net.glowstone.net.message.login.EncryptionKeyResponseMessage@5ad59375 (handler: EncryptionKeyResponseHandler)
java.util.NoSuchElementException: encryption
    at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:907)
    at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:377)
    at net.glowstone.net.GlowSession.updatePipeline(GlowSession.java:404)
    at net.glowstone.net.GlowSession.enableEncryption(GlowSession.java:390)
    at net.glowstone.net.handler.login.EncryptionKeyResponseHandler.handle(EncryptionKeyResponseHandler.java:78)
    at net.glowstone.net.handler.login.EncryptionKeyResponseHandler.handle(EncryptionKeyResponseHandler.java:33)
    at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:82)
    at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:141)
    at net.glowstone.net.GlowSession.pulse(GlowSession.java:356)
    at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:172)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:109)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
```

**Comment by turt2live** [comment]
Couldn't reproduce this personally. May be a strange case to reproduce.

**Comment by SpaceManiac** [comment]
I was able to reproduce this by spamming connecting and cancelling repeatedly.
