### ISSUE TITLE
Add 1.7.x plugins support.

### ISSUE THREAD

**Issue by Leymooo** [GlowstoneMC/Glowstone-Legacy#159]
Add 1.7.x plugins support.

**Comment by lukespragg** [comment]
What is specific about 1.7.x plugins? Generally all plugins that use purely the Bukkit API should work, granted the API methods they use are fully integrated. Any plugins with NMS calls will not work though.

**Comment by SpaceManiac** [comment]
Glowstone currently supports Bukkit plugins written for Bukkit 1.7.9-R0.1 and earlier (and newer plugins that do not rely on new behavior). What compatibility problems are you having?

**Comment by Leymooo** [comment]
authme 
2014/09/05 13:00:00 [SEVERE] Could not pass event PlayerLoginEvent to AuthMe v3.3.6
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
    at net.glowstone.EventFactory$1.run(EventFactory.java:51)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.glowstone.scheduler.GlowScheduler.scheduleInTickExecution(GlowScheduler.java:154)
    at net.glowstone.EventFactory.callEvent(EventFactory.java:54)
    at net.glowstone.EventFactory.onPlayerLogin(EventFactory.java:131)
    at net.glowstone.net.GlowSession.setPlayer(GlowSession.java:244)
    at net.glowstone.net.handler.login.EncryptionKeyResponseHandler$ClientAuthThread$1.run(EncryptionKeyResponseHandler.java:158)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.glowstone.scheduler.GlowTask.run(GlowTask.java:163)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:180)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:109)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at fr.xephi.authme.listener.AuthMePlayerListener.onPlayerLogin(AuthMePlayerListener.java:390)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292)
    ... 24 more
2014/09/05 13:00:00 [INFO] dimatert9 [/127.0.0.1:51556] connected, UUID: cb9bd237-c8cb-4b0a-a435-047e43c27470
2014/09/05 13:00:00 [INFO] [mcjobs] Unable to load dimatert9.dat...  Creating file!
2014/09/05 13:00:00 [INFO] [mcjobs] Creating player data directory...
2014/09/05 13:00:00 [INFO] [mcjobs] Your permission mod does not support player groups.  Using default max jobs only.
2014/09/05 13:00:00 [SEVERE] Could not find spawn.yml, creating new one...
2014/09/05 13:00:00 [SEVERE] Could not pass event PlayerJoinEvent to AuthMe v3.3.6
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
    at net.glowstone.EventFactory$1.run(EventFactory.java:51)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.glowstone.scheduler.GlowScheduler.scheduleInTickExecution(GlowScheduler.java:154)
    at net.glowstone.EventFactory.callEvent(EventFactory.java:54)
    at net.glowstone.EventFactory.onPlayerJoin(EventFactory.java:81)
    at net.glowstone.net.GlowSession.setPlayer(GlowSession.java:254)
    at net.glowstone.net.handler.login.EncryptionKeyResponseHandler$ClientAuthThread$1.run(EncryptionKeyResponseHandler.java:158)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.glowstone.scheduler.GlowTask.run(GlowTask.java:163)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:180)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:109)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at net.milkbowl.vault.permission.plugins.Permission_GroupManager.getPrimaryGroup(Permission_GroupManager.java:327)
    at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:644)
    at fr.xephi.authme.cache.limbo.LimboCache.addLimboPlayer(LimboCache.java:72)
    at fr.xephi.authme.listener.AuthMePlayerListener.onPlayerJoin(AuthMePlayerListener.java:691)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292)
    ... 24 more

**Comment by Leymooo** [comment]
ChatGuard
2014/09/05 13:00:13 [SEVERE] Could not pass event PlayerCommandPreprocessEvent to ChatGuard v6.2
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
    at net.glowstone.EventFactory$1.run(EventFactory.java:51)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.glowstone.scheduler.GlowScheduler.scheduleInTickExecution(GlowScheduler.java:154)
    at net.glowstone.EventFactory.callEvent(EventFactory.java:54)
    at net.glowstone.EventFactory.onPlayerCommand(EventFactory.java:77)
    at net.glowstone.entity.GlowPlayer.chat(GlowPlayer.java:1090)
    at net.glowstone.net.handler.play.game.ChatHandler.handle(ChatHandler.java:11)
    at net.glowstone.net.handler.play.game.ChatHandler.handle(ChatHandler.java:7)
    at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
    at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
    at net.glowstone.net.GlowSession.pulse(GlowSession.java:356)
    at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:172)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:109)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.StackOverflowError
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)
    at ru.Den_Abr.ChatGuard.Handlers.CmdHandler.onPlayerCommand(CmdHandler.java:70)

**Comment by Leymooo** [comment]
essentialsgroupmanage
14/09/06 14:00:45 [WARNING] GroupManager - SEVERE - ===================================================
2014/09/06 14:00:45 [WARNING] GroupManager - SEVERE - === PLEASE COPY AND PASTE THE ERROR.LOG FROM THE ==
2014/09/06 14:00:45 [WARNING] GroupManager - SEVERE - = GROUPMANAGER FOLDER TO AN ESSENTIALS  DEVELOPER =
2014/09/06 14:00:45 [WARNING] GroupManager - SEVERE - ===================================================
2014/09/06 14:00:45 [WARNING] GroupManager - SEVERE - null
2014/09/06 14:00:45 [WARNING] GroupManager - SEVERE - ===================================================
2014/09/06 14:00:45 [WARNING] GroupManager - SEVERE - = ERROR REPORT ENDED =
2014/09/06 14:00:45 [WARNING] GroupManager - SEVERE - ===================================================
2014/09/06 14:00:45 [SEVERE] Error occurred while enabling GroupManager v2.0 (2.12.1) (Phoenix) (Is it up to date?)
java.lang.IllegalArgumentException
    at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:238)
    at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:93)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
    at net.glowstone.GlowServer.enablePlugins(GlowServer.java:510)
    at net.glowstone.GlowServer.start(GlowServer.java:361)
    at net.glowstone.GlowServer.main(GlowServer.java:87)
Caused by: java.lang.NullPointerException
    at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.setupWorldFolder(WorldsHolder.java:542)
    at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.verifyFirstRun(WorldsHolder.java:536)
    at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.resetWorldsHolder(WorldsHolder.java:91)
    at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.<init>(WorldsHolder.java:59)
    at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:169)
    ... 7 more

**Comment by Leymooo** [comment]
world guard
Could not pass event PlayerInteractEvent to WorldGuard v6.0.0-SNAPSHOT.1463-
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
    at net.glowstone.EventFactory$1.run(EventFactory.java:51)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.glowstone.scheduler.GlowScheduler.scheduleInTickExecution(GlowScheduler.java:154)
    at net.glowstone.EventFactory.callEvent(EventFactory.java:54)
    at net.glowstone.EventFactory.onPlayerInteract(EventFactory.java:105)
    at net.glowstone.net.handler.play.player.BlockPlacementHandler.handle(BlockPlacementHandler.java:94)
    at net.glowstone.net.handler.play.player.BlockPlacementHandler.handle(BlockPlacementHandler.java:23)
    at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
    at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
    at net.glowstone.net.GlowSession.pulse(GlowSession.java:363)
    at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:172)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:109)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.handleBlockRightClick(WorldGuardPlayerListener.java:523)
    at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerInteract(WorldGuardPlayerListener.java:460)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292)
    ... 25 more

**Comment by NewbieOrange** [comment]
It seems that the server returned null objects to the listeners.

**Comment by turt2live** [comment]
Looks like an API completeness problem. I don't see anything that would be a glowstone problem besides the obvious plugin-induced failure (which is really, technically, plugin failure).

Please correct me ASAP if I'm wrong.

**Comment by turt2live** [comment]
(Closing this for now - please respond if there are any updates to have it reopened)
