### ISSUE TITLE
ClearLagg's area command needs GlowEntity.getNearbyEntities()

### ISSUE THREAD

**Issue by dequis** [GlowstoneMC/Glowstone-Legacy#261]
It complains about `Thats not an integer`, but the exact same command in craftbukkit works.

Oddly, `/lagg tpchunk <x> <z> <world>` works.

Yes I know it's a command about entities and there are none to clear

**Comment by SpaceManiac** [comment]
The answer probably lies in ClearLagg's code for that command. More likely than not, it has some try/catch block which both parses the number and performs the action, and a catch block that assumes the error came from parsing the number (hiding the fact that the error was in the action - probably due to some underlying missing implementation).

**Comment by dequis** [comment]
Decompiled, remove try...catch, recompiled:

```
org.bukkit.command.CommandException: Unhandled exception executing command 'lagg' in plugin ClearLag v2.7.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180)
        at net.glowstone.GlowServer.dispatchCommand(GlowServer.java:763)
        at net.glowstone.entity.GlowPlayer.chat(GlowPlayer.java:1169)
        at net.glowstone.net.handler.play.game.ChatHandler.handle(ChatHandler.java:11)
        at net.glowstone.net.handler.play.game.ChatHandler.handle(ChatHandler.java:7)
        at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
        at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
        at net.glowstone.net.GlowSession.pulse(GlowSession.java:362)
        at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:174)
        at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:25)
        at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:111)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException: Not supported yet.
        at net.glowstone.entity.GlowEntity.getNearbyEntities(GlowEntity.java:498)
        at me.minebuilders.clearlag.commands.AreaCmd.run(AreaCmd.java:37)
        at me.minebuilders.clearlag.modules.CommandModule.processCmd(CommandModule.java:39)
        at me.minebuilders.clearlag.CommandListener.onCommand(CommandListener.java:26)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        ... 19 more
```

So yeah. `GlowEntity.getNearbyEntities` not supported yet.

**Comment by JeromSar** [comment]
Working on this tonight.

**Comment by dequis** [comment]
\o/

**Comment by SpaceManiac** [comment]
Take a look at 05d7714886e6713e37b37c24efbc2e59ae83b365 on the `entities` branch regarding this. It's only a partial implementation but it's a starting point (someone else, I forget who, who was working on entities includes this commit in their branch).

**Comment by JeromSar** [comment]
@SpaceManiac I suppose it would be better to wait for that branch to merge. :)

**Comment by gdude2002** [comment]
[We build this](http://bamboo.gserv.me/browse/GLOW-SRV1/latest), we should probably test again.

**Comment by SpaceManiac** [comment]
Commit 474be7da implements `getNearbyEntities()`. Could someone check things are fixed in ClearLagg?

Edit: w/e, just considering this closed since the method is implemented. Reopen or open another if problem persists.
