### ISSUE TITLE
getItemInHand() returns null instead of ItemStack{AIR x 0}

### ISSUE THREAD

**Issue by dequis** [GlowstoneMC/Glowstone-Legacy#265]
....which results in NPEs being thrown when right clicking blocks with WorldGuard

```
03:20:01 [SEVERE] Could not pass event PlayerInteractEvent to WorldGuard v5.9
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
        at net.glowstone.EventFactory$1.run(EventFactory.java:51)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at net.glowstone.scheduler.GlowScheduler.scheduleInTickExecution(GlowScheduler.java:156)
        at net.glowstone.EventFactory.callEvent(EventFactory.java:54)
        at net.glowstone.EventFactory.onPlayerInteract(EventFactory.java:105)
        at net.glowstone.net.handler.play.player.BlockPlacementHandler.handle(BlockPlacementHandler.java:95)
        at net.glowstone.net.handler.play.player.BlockPlacementHandler.handle(BlockPlacementHandler.java:23)
        at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
        at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
        at net.glowstone.net.GlowSession.pulse(GlowSession.java:362)
        at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:174)
        at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:25)
        at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:111)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.sk89q.worldguard.bukkit.WorldGuardPlayerListener.handleBlockRightClick(WorldGuardPlayerListener.java:707)
        at com.sk89q.worldguard.bukkit.WorldGuardPlayerListener.onPlayerInteract(WorldGuardPlayerListener.java:493)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292)
        ... 25 more
```

Relevant source code:

https://github.com/sk89q/WorldGuard/blob/5.9/src/main/java/com/sk89q/worldguard/bukkit/WorldGuardPlayerListener.java#L707

**Comment by SpaceManiac** [comment]
The only thing that could be null on that line is `item`, the player's item in hand, which is indeed sometimes null... maybe the `isCancelled()` is supposed to be returning true, or there's some weird behavior with item in hand being AIR?

**Comment by dequis** [comment]
Indeed only happens when the item in hand is AIR

**Comment by dequis** [comment]
It's getItemInHand() returning null. Craftbukkit returns ItemStack{AIR x 0}

Updating title.

**Comment by dequis** [comment]
ADVANCED DEBUGGING TECHNIQUES.

```
Logger log = getLogger();
Player p = ((Player) sender);
PlayerInventory inv = p.getInventory();

log.info("item in hand: " + inv.getItemInHand());
log.info("boots " + inv.getBoots());
log.info("chestplate " + inv.getChestplate());
log.info("helmet " + inv.getHelmet());
log.info("getitem 0 " + inv.getItem(0));

for (ItemStack i : inv.getContents()) {
    log.info("inventory contents: " + i);
}
```

Output:

```
[05:31:52 INFO]: [Test] item in hand: ItemStack{AIR x 0}
[05:31:52 INFO]: [Test] boots null
[05:31:52 INFO]: [Test] chestplate null
[05:31:52 INFO]: [Test] helmet null
[05:31:52 INFO]: [Test] getitem 0 null
[05:31:52 INFO]: [Test] inventory contents: null
[05:31:52 INFO]: [Test] inventory contents: ItemStack{SAPLING x 1}
[05:31:52 INFO]: [Test] inventory contents: null
[05:31:52 INFO]: [Test] inventory contents: ItemStack{GRASS x 1}
[05:31:52 INFO]: [Test] inventory contents: null
[05:31:52 INFO]: [Test] inventory contents: null
[05:31:52 INFO]: [Test] inventory contents: null
...etc...
```

Going to go ahead and just patch `getItemInHand()`

**Comment by dequis** [comment]
Well that failed and i'm too tired to figure it out. Quoting myself from the now-closed PR:

> Bleh, this breaks PlayerInteractEvent for some reason when ItemStack{AIR x 0} is returned. I'm doing something very wrong here. Closing until I figure it out.

**Comment by SpaceManiac** [comment]
I acknowledge that this is the behavior but I'm not certain it's worth trying to fix - the API doesn't really specify which is correct and it's always been my personal opinion that `null` makes much more sense than an `AIR` stack - which is also the behavior everywhere else, I'm fairly sure... (except maybe armor slots - I'd need to check those on CB).

**Comment by dequis** [comment]
The tests above were with spigot 1649 (the 1.8 protocol hack, the only thing i had here). I tried to test all functions that return ItemStack from the Inventory / PlayerInventory interface, and getItemInHand was the only one which returned an empty AIR stack.

I dunno. I do agree that null makes more sense. It's just not what plugins expect.

**Comment by SpaceManiac** [comment]
Considering this closed unless it eventually proves ridiculously problematic. I'd prefer for now to maintain internal consistency over compatibility with one of the most annoying corner cases in Bukkit.

**Comment by dequis** [comment]
This one was found in XpInTheJar too:

https://gist.github.com/bendem/fd21f153a00a9f179a25
https://github.com/bendem/XP-in-the-Jar/blob/master/src/main/java/cc/thedudeguy/xpinthejar/XPInTheJar.java#L54

**Comment by dequis** [comment]
Found in mcMMO too

https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/listeners/BlockListener.java#L171

```
ItemStack heldItem = player.getItemInHand();
...
... && ItemUtils.isPickaxe(heldItem) && ...
...
Material type = item.getType();
```
