### ISSUE TITLE
Remapper not working quite right

### ISSUE THREAD

**Issue by dequis** [GlowstoneMC/Glowstone-Legacy#268]
Fails with NCore v0.6.9 (which compiles against 1.7.9 api), these exceptions are thrown in an scheduled task that runs ~30 seconds after server startup (needs an extra plugin such as NWorld to not disable itself, should probably find a plugin that makes this easier to reproduce, but whatever)

Using `glowstone-0.0.1-SNAPSHOT-remapped.jar`:

```
19:11:13 [SEVERE] [NCore] Error while executing GlowTask{id=875, plugin=NCore v0.6.9, sync=true: fr.ribesg.bukkit.ncore.updater.UpdaterTask$1@756b9292}
java.lang.NoSuchMethodError: org.bukkit.Server._INVALID_getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at org.bukkit.Bukkit.getOnlinePlayers(Bukkit.java:103)
        at fr.ribesg.bukkit.ncore.updater.UpdaterTask$1.run(UpdaterTask.java:31)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at net.glowstone.scheduler.GlowTask.run(GlowTask.java:163)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:182)
        at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:25)
        at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:111)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
>
```

As suggested by @gdude2002 on irc, I tried the `-all` jar. (`< g> remapped is for a very specific purpose, and this isn't it`)

Using `glowstone-0.0.1-SNAPSHOT-all.jar`

```
20:54:16 [SEVERE] [NCore] Error while executing GlowTask{id=7, plugin=NCore v0.6.9, sync=true: fr.ribesg.bukkit.ncore.updater.UpdaterTask$1@50866ce2}
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at fr.ribesg.bukkit.ncore.updater.UpdaterTask$1.run(UpdaterTask.java:31)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at net.glowstone.scheduler.GlowTask.run(GlowTask.java:163)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:182)
        at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:25)
        at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:111)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

So `-all` probably isn't the right one either. I'd appreciate some clarification on this, since I suspect @gdude2002 is _full of shit_.

**Comment by SpaceManiac** [comment]
Ncore is trying to access two mutually exclusive methods... either the _INVALID_ method exists or the renamed method with the same signature exists. No plugin should ever explicitly call the former.

**Comment by dequis** [comment]
Weird:

https://github.com/Ribesg/NPlugins/blob/9ecc5914fe127a95dcae66c1eacdb274a8d7032b/NCore/src/main/java/fr/ribesg/bukkit/ncore/updater/UpdaterTask.java#L31

(edit: updated link to point to 0.6.9 and correct line number)

@ribesg

**Comment by dequis** [comment]
And while i'm pinging everyone, @games647 also ran into issues with the remapper: https://github.com/games647/ScoreboardStats/issues/32#issuecomment-55451591

**Comment by SpaceManiac** [comment]
Ah - I think I see the problem. I'll work on it when I can.

For reference: remapper does not remap _calls_ to remapped functions - so the remapped `Bukkit` method tries to call the non-remapped method on `Server` but can't find it. The remapper needs to remap this call also.
