### ISSUE TITLE
Could not pass event PlayerInteractEvent to TNTSweeper v1.0b

### ISSUE THREAD

**Issue by dequis** [GlowstoneMC/Glowstone-Legacy#311]
Another one for this plugin.

```
02:47:18 [SEVERE] Could not pass event PlayerInteractEvent to TNTSweeper v1.0b
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
        at net.glowstone.EventFactory$1.run(EventFactory.java:48)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at net.glowstone.scheduler.GlowScheduler.scheduleInTickExecution(GlowScheduler.java:156)
        at net.glowstone.EventFactory.callEvent(EventFactory.java:51)
        at net.glowstone.EventFactory.onPlayerInteract(EventFactory.java:163)
        at net.glowstone.net.handler.play.player.BlockPlacementHandler.handle(BlockPlacementHandler.java:95)
        at net.glowstone.net.handler.play.player.BlockPlacementHandler.handle(BlockPlacementHandler.java:23)
        at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
        at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
        at net.glowstone.net.GlowSession.pulse(GlowSession.java:381)
        at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:174)
        at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:25)
        at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:111)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException
        at java.util.Collections$UnmodifiableCollection.clear(Collections.java:1094)
        at com.craftererer.plugins.tntsweeper.TNTSweeperBoard.setFlag(TNTSweeperBoard.java:374)
        at com.craftererer.plugins.tntsweeper.TNTSweeperListener.onPlayerClick(TNTSweeperListener.java:77)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292)
        ... 25 more
```

Does not seem to be open source, despite the bukkitdev page claiming it is.

Lazy bug report because I'm tired.

**Comment by SpaceManiac** [comment]
`clickedBlock.getDrops().clear();`
Calling broken plugin on this one, this behavior makes no sense.
