### ISSUE TITLE
Strange protocol problem

### ISSUE THREAD

**Issue by turt2live** [GlowstoneMC/Glowstone-Legacy#418]
I couldn't find a directly related ticket, but I did get this exception on a public-facing test server overnight.

```
03:01:08 [SEVERE] Error in network input
io.netty.handler.codec.DecoderException: com.flowpowered.networking.exception.IllegalOpcodeException: Opcode 69 is not bound!
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.flowpowered.networking.exception.IllegalOpcodeException: Opcode 69 is not bound!
        at com.flowpowered.networking.service.CodecLookupService.find(CodecLookupService.java:163)
        at net.glowstone.net.protocol.GlowProtocol.newReadHeader(GlowProtocol.java:101)
        at net.glowstone.net.pipeline.CodecsHandler.decode(CodecsHandler.java:50)
        at net.glowstone.net.pipeline.CodecsHandler.decode(CodecsHandler.java:19)
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
        ... 16 more
03:01:23 [INFO] [/IP REDACTED:58931] kicked: Timed out
```

IP is located in `Tianjin, Tianjin, China` according to Ultros on espernet.

**Comment by dequis** [comment]
I can reproduce this one by doing a goddamn HTTP request to http://localhost:25565/

**Comment by turt2live** [comment]
Confirmed. Wow.

Full HTTP log: [log](http://i.turt2live.com/IVoy.txt)

**Comment by dequis** [comment]
I get only one when requesting with curl. Probably just some bot portscanning you.

This one should be fixed by kicking misbehaving clients, just like vanilla does.

**Comment by turt2live** [comment]
I just punched it in to my web browser.

**Comment by coelho** [comment]
Rather than a bug I think this is just more of an exception that should be suppressed or made finer.

**Comment by dequis** [comment]
Sure, but keeping the connection open until it timeouts is also incorrect.

**Comment by coelho** [comment]
Oh yes, if there's a codec exception like this the connection should be immediately closed.

**Comment by turt2live** [comment]
Closing this to clean up my issues list on Github. If this is still an issue, please port it over to https://github.com/GlowstoneMC/Glowstone
