### ISSUE TITLE
Teleporting player to null world messes up future location packets

### ISSUE THREAD

**Issue by daboross** [GlowstoneMC/Glowstone-Legacy#475]
Though this is caused by a faulty plugin, I thought I might mention that if you call `player.teleport(null, 0, 0, 0)`, there will be a nullpointerexception in GlowPlayer, _and_ future packets will be messed up.

I think it might be better to check for this and throw an NullPointerException purposefully, and then not mess up future packets.

```
Caused by: java.lang.NullPointerException
    at net.glowstone.entity.GlowPlayer.spawnAt(GlowPlayer.java:584)
    at net.glowstone.entity.GlowPlayer.teleport(GlowPlayer.java:1157)
    at net.glowstone.entity.GlowPlayer.teleport(GlowPlayer.java:1143)
    at net.daboross.bukkitdev.skywars.game.GameHandler.respawnPlayer(GameHandler.java:134)
    at ...
```

```
2014/10/23 12:29:56 [SEVERE] Error while handling PlayerPositionMessage(onGround=false, x=4.9818027177279705, y=-992.6619695044176, z=1.7616845153779592) (handler: PlayerUpdateHandler)
java.lang.IllegalArgumentException: Cannot setRawLocation to a different world (got GlowWorld{name='SkyWarsArenaWorld'}, expected null)
    at net.glowstone.entity.GlowEntity.setRawLocation(GlowEntity.java:361)
    at net.glowstone.net.handler.play.player.PlayerUpdateHandler.handle(PlayerUpdateHandler.java:24)
    at net.glowstone.net.handler.play.player.PlayerUpdateHandler.handle(PlayerUpdateHandler.java:8)
    at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
    at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
    at net.glowstone.net.GlowSession.pulse(GlowSession.java:408)
    at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:174)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:25)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:111)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by turt2live** [comment]
What is CraftBukkit behaviour?

**Comment by bendem** [comment]
CB fails should fail after calling the event, throwing a NPE from the `teleport` method before doing anything:

``` java
WorldServer toWorld = ((CraftWorld) to.getWorld()).getHandle();
```

would fail since `to` is null

Glowstone should maybe validate the location parameter directly or after the EventFactory.callEvent (I'd say both).
