### ISSUE TITLE
factions and mcore do not work at all or load up in glowstone

### ISSUE THREAD

**Issue by efrank123456789** [GlowstoneMC/Glowstone-Legacy#476]
so i put factions and mcore in the plugins folder and it did not work and i was hoping to make a factions server with glowstone but i cannot if factions is not supported for glowstone so please make factions and mcore compatible with glowstone

**Comment by bendem** [comment]
https://github.com/GlowstoneMC/Glowstone/wiki/Plugin-Compatibility

**Comment by efrank123456789** [comment]
so that means that it wont work at all.....

**Comment by bendem** [comment]
That means that it doesn't work at the moment because it needs to be updated to work with glowstone once glowstone is actually done.

**Comment by dequis** [comment]
Linking that page and jumping to the conclusion that "it won't work at all" isn't particularly helpful. Where are the error messages?

**Comment by dequis** [comment]
```
17:25:12 [SEVERE] Could not load 'plugins/MassiveCore.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R4/PlayerInventory
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251)
        at net.glowstone.GlowServer.loadPlugins(GlowServer.java:561)
        at net.glowstone.GlowServer.start(GlowServer.java:383)
        at net.glowstone.GlowServer.main(GlowServer.java:91)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R4/PlayerInventory
        at com.massivecraft.massivecore.MassiveCore.getMassiveCoreGsonBuilder(MassiveCore.java:85)
        at com.massivecraft.massivecore.MassiveCore.<clinit>(MassiveCore.java:70)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:270)
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R4.PlayerInventory
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 11 more
```

MCore depends on net.minecraft.server, Factions 2.x depends on MCore. They will need to be updated to support glowstone by their developers.
