### ISSUE TITLE
Fails to allow execution of file "start.command" on Mac.

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone-Legacy#504]
When I try to open start.command on my mac, I get a error message that says...
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/glowstone/GlowServer : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
logout

[Process completed]

What does this mean and how can i fix it.
I am running Java Version 8 Update 25.

**Comment by dequis** [comment]
That really sounds like you're using java6 to start it, even if you have java8 installed somewhere else

**Comment by choyiny** [comment]
https://gist.github.com/johan/10590467

**Comment by turt2live** [comment]
User has been deleted. Closing.

**Comment by dequis** [comment]
Huh. Spooky.
