### ISSUE TITLE
Internal Error During Authentication (unable to join own server)

### ISSUE THREAD

**Issue by LimitlessGamingmelon** [GlowstoneMC/Glowstone-Legacy#579]
Whenever I try to join my server, it begins loading, then tells me:
"Failed to connect to the server Internal Error during authentication"
Any ideas?

**Comment by turt2live** [comment]
Please provide both the client and server logs.

**Comment by LimitlessGamingmelon** [comment]
```
2014/11/29 17:44:40 [INFO] Preparing spawn for world...
2014/11/29 17:44:41 [INFO] Preparing spawn for world: 18%
2014/11/29 17:44:42 [INFO] Preparing spawn for world: 43%
2014/11/29 17:44:43 [INFO] Preparing spawn for world: 66%
2014/11/29 17:44:44 [INFO] Preparing spawn for world: 90%
2014/11/29 17:44:44 [INFO] Preparing spawn for world: done
2014/11/29 17:44:44 [INFO] Preparing spawn for world_nether...
2014/11/29 17:44:46 [INFO] Preparing spawn for world_nether: 35%
2014/11/29 17:44:47 [INFO] Preparing spawn for world_nether: 75%
2014/11/29 17:44:47 [INFO] Preparing spawn for world_nether: done
2014/11/29 17:44:47 [INFO] Preparing spawn for world_the_end...
2014/11/29 17:44:48 [INFO] Preparing spawn for world_the_end: 89%
2014/11/29 17:44:48 [INFO] Preparing spawn for world_the_end: done
2014/11/29 17:44:48 [INFO] Created default config: config\commands.yml
2014/11/29 17:44:49 [INFO] Created default config: config\permissions.yml
2014/11/29 17:44:49 [INFO] Binding to address: 0.0.0.0/0.0.0.0:25565...
2014/11/29 17:44:49 [SEVERE] Error during server startup.
java.lang.RuntimeException: Failed to bind to address. Maybe it is already in use?
    at net.glowstone.GlowServer.bind(GlowServer.java:415)
    at net.glowstone.GlowServer.main(GlowServer.java:91)
2014/11/29 17:50:48 [INFO] Preparing spawn for world...
2014/11/29 17:50:49 [INFO] Preparing spawn for world: 22%
2014/11/29 17:50:50 [INFO] Preparing spawn for world: 46%
2014/11/29 17:50:52 [INFO] Preparing spawn for world: 67%
2014/11/29 17:50:53 [INFO] Preparing spawn for world: 93%
2014/11/29 17:50:53 [INFO] Preparing spawn for world: done
2014/11/29 17:50:53 [INFO] Preparing spawn for world_nether...
2014/11/29 17:50:54 [INFO] Preparing spawn for world_nether: 38%
2014/11/29 17:50:55 [INFO] Preparing spawn for world_nether: 82%
2014/11/29 17:50:55 [INFO] Preparing spawn for world_nether: done
2014/11/29 17:50:55 [INFO] Preparing spawn for world_the_end...
2014/11/29 17:50:56 [INFO] Preparing spawn for world_the_end: 86%
2014/11/29 17:50:56 [INFO] Preparing spawn for world_the_end: done
2014/11/29 17:50:57 [INFO] Binding to address: 0.0.0.0/0.0.0.0:25565...
2014/11/29 17:50:57 [INFO] Ready for connections.
2014/11/29 17:57:43 [SEVERE] Error in authentication thread
javax.net.ssl.SSLProtocolException: Signature algorithm mismatch
    at sun.security.ssl.HandshakeMessage$CertificateMsg.<init>(Unknown Source)
    at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
    at sun.security.ssl.Handshaker.processLoop(Unknown Source)
    at sun.security.ssl.Handshaker.process_record(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
    at net.glowstone.net.handler.login.EncryptionKeyResponseHandler$ClientAuthRunnable.run(EncryptionKeyResponseHandler.java:124)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.security.cert.CertificateException: Signature algorithm mismatch
    at sun.security.x509.X509CertImpl.parse(Unknown Source)
    at sun.security.x509.X509CertImpl.<init>(Unknown Source)
    at sun.security.provider.X509Factory.engineGenerateCertificate(Unknown Source)
    at java.security.cert.CertificateFactory.generateCertificate(Unknown Source)
    ... 14 more
2014/11/29 17:57:43 [INFO] [/127.0.0.1:58267] kicked: Internal error during authentication.
2014/11/29 18:07:49 [SEVERE] Error in authentication thread
javax.net.ssl.SSLProtocolException: Signature algorithm mismatch
    at sun.security.ssl.HandshakeMessage$CertificateMsg.<init>(Unknown Source)
    at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
    at sun.security.ssl.Handshaker.processLoop(Unknown Source)
    at sun.security.ssl.Handshaker.process_record(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
    at net.glowstone.net.handler.login.EncryptionKeyResponseHandler$ClientAuthRunnable.run(EncryptionKeyResponseHandler.java:124)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.security.cert.CertificateException: Signature algorithm mismatch
    at sun.security.x509.X509CertImpl.parse(Unknown Source)
    at sun.security.x509.X509CertImpl.<init>(Unknown Source)
    at sun.security.provider.X509Factory.engineGenerateCertificate(Unknown Source)
    at java.security.cert.CertificateFactory.generateCertificate(Unknown Source)
    ... 14 more
2014/11/29 18:07:49 [INFO] [/127.0.0.1:58505] kicked: Internal error during authentication.
```

^^ Well, this is the only log it has for the server, but what do you mean by client log? (Sorry it was long, not sure if I could send a file)

**Comment by PaulBGD** [comment]
No, that's perfect. Thank you.

**Comment by turt2live** [comment]
Looks like your server failed to bind, which may cause issues.

Make sure that your server is not running elsewhere.

**Comment by turt2live** [comment]
@LimitlessGamingmelon Were you able to resolve the issue?

**Comment by LimitlessGamingmelon** [comment]
Not yet, but thanks for helping me with my problem!

**Comment by SpaceManiac** [comment]
The only thing I can gather is that your connection to https://sessionserver.mojang.com/ is somehow broken. Are you able to access this website in the browser or through wget from the problematic machine? What results do you get?

**Comment by gdude2002** [comment]
The person that submitted this ticket hasn't responded in almost a month (with the last official response almost two weeks ago).

If you haven't solved your problem, @LimitlessGamingmelon, please feel free to comment on this ticket or post a topic on [the forums](https://forums.glowstone.net).
