### ISSUE TITLE
Bukkit plugins on GlowstoneMC

### ISSUE THREAD

**Issue by Djani9892** [GlowstoneMC/Glowstone-Legacy#584]
Hello! I put World Edit and now error in console but plugin work.. What is wrong?

14:02:38 [WARNING] Error loading entity in GlowChunk{world=world,x=8,z=15}
java.lang.IllegalArgumentException: Unknown entity type to load: "Rabbit"
        at net.glowstone.io.entity.EntityStorage.loadEntity(EntityStorage.java:6
6)
        at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.j
ava:107)
        at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:123)
        at net.glowstone.GlowChunk.load(GlowChunk.java:300)
        at net.glowstone.GlowChunk.load(GlowChunk.java:295)
        at net.glowstone.GlowWorld.loadChunk(GlowWorld.java:867)
        at net.glowstone.GlowWorld.<init>(GlowWorld.java:317)
        at net.glowstone.GlowServer.createWorld(GlowServer.java:1200)
        at net.glowstone.GlowServer.start(GlowServer.java:416)
        at net.glowstone.GlowServer.main(GlowServer.java:94)
14:02:38 [WARNING] Error loading entity in GlowChunk{world=world,x=8,z=16}
java.lang.IllegalArgumentException: Unknown entity type to load: "Rabbit"
        at net.glowstone.io.entity.EntityStorage.loadEntity(EntityStorage.java:6
6)
        at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.j
ava:107)

**Comment by gdude2002** [comment]
Pretty much as the error says, there's an unknown entity in the chunk - a rabbit, by the looks of it.

Glowstone isn't feature-complete yet and is intended for development purposes only, until we've finished getting everything working.

Please see [here](https://github.com/GlowstoneMC/Glowstone/wiki/Frequently-Asked-Questions#insert-feature-here-doesnt-work) and [here](https://github.com/GlowstoneMC/Glowstone/wiki/Current-Features) for more information.

**Comment by Djani9892** [comment]
Okay Thanks! :)
