### ISSUE TITLE
EssentialsChat not Working (Prefixes/Suffixes not working with PermissionsEX)

### ISSUE THREAD

**Issue by FlubberDunkies** [GlowstoneMC/Glowstone-Legacy#593]
Hi,
I've been trying to set up a server with prefixes and suffixes using both PermissionsEX, and EssentialsChat. Currently, PermissionsEX is working fine, but I'm encountering a error along with Essentials chat along of this string:

```
2014/12/20 08:11:54 [INFO] funnyboneslamer [/127.0.0.1:50825] connected, UUID: ef61358c-df23-496c-bf15-4ec8489ce58f
2014/12/20 08:11:54 [INFO] §efunnyboneslamer joined the game
2014/12/20 08:11:59 [SEVERE] Could not pass event AsyncPlayerChatEvent to EssentialsChat vPre2.14.1.3
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483)
    at net.glowstone.EventFactory.callEvent(EventFactory.java:42)
    at net.glowstone.EventFactory.onPlayerChat(EventFactory.java:120)
    at net.glowstone.entity.GlowPlayer.chat(GlowPlayer.java:1300)
    at net.glowstone.net.handler.play.game.IncomingChatHandler.handle(IncomingChatHandler.java:11)
    at net.glowstone.net.handler.play.game.IncomingChatHandler.handle(IncomingChatHandler.java:7)
    at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
    at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
    at net.glowstone.net.GlowSession.messageReceived(GlowSession.java:493)
    at net.glowstone.net.pipeline.MessageHandler.channelRead0(MessageHandler.java:49)
    at net.glowstone.net.pipeline.MessageHandler.channelRead0(MessageHandler.java:15)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
    at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at com.earth2me.essentials.chat.EssentialsChatPlayerListenerLowest.onPlayerChat(EssentialsChatPlayerListenerLowest.java:50)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292)
    ... 41 more
```

Currently, all I'm getting out of this is that EssentialsChat is no longer functioning with Glowstone, because of something I am completely unaware of. Also, I have tried using all versions of EssentialsChat, ranking down to 1.0, to Bleeding-Edge versions, so I'm assuming this has to do with Glowstones 104th update. I hope you guys can fix this soon. :/

**Comment by gdude2002** [comment]
That's a NullPointerException in the EssentialsChat plugin.. I assume you had it working on an earlier version of Glowstone?

I'm not entirely sure what causes this, paging @turt2live in case he knows.

**Comment by FlubberDunkies** [comment]
No, I've just tried earlier builds of Glowstone, and it is still nonfunctional, and I don't know how to fix it. All the issue is is that its keeping to the default chat tags of Minecraft being the "< Namehere >" "Chathere" kinda deal.

**Comment by Johni0702** [comment]
This is most likely [caused by](https://github.com/essentials/Essentials/blob/a2c43d822c66e617a84df9a8f074b9c3a3e32fae/EssentialsChat/src/com/earth2me/essentials/chat/EssentialsChatPlayerListenerLowest.java#L50) scoreboards not yet being functional as far as I can tell.

**Comment by turt2live** [comment]
This is a known issue due to scoreboards. 

Glowstone is not yet complete and should be used for development or evaluation purposes only. We do not recommend using Glowstone on your live server without some serious and heavy investigation on what is complete and what is not complete for your needs.
