### ISSUE TITLE
PermissionEx Faild to Load

### ISSUE THREAD

**Issue by DefinitlyEvil** [GlowstoneMC/Glowstone-Legacy#604]
It seems to be some 3rd-party library missing. 

Details:

```
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;
    at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
    at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
    at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
    at net.glowstone.GlowServer.enablePlugins(GlowServer.java:710)
    at net.glowstone.GlowServer.start(GlowServer.java:461)
    at net.glowstone.GlowServer.main(GlowServer.java:112)
```

**Comment by gdude2002** [comment]
As the [plugin compatibility list](https://github.com/GlowstoneMC/Glowstone/wiki/Plugin-Compatibility) states, you must use version 1.22.6 or lower - 1.23 isn't supported.

**Comment by DefinitlyEvil** [comment]
Sorry about this, but why isn't it supported?

**Comment by kamcio96** [comment]
guava version

**Comment by DefinitlyEvil** [comment]
@kamcio96 Oh, I see.

**Comment by gdude2002** [comment]
Basically, Spigot uses a later version of Google's Guava than base Bukkit/Craftbukkit does - since we're a Bukkit replacement rather than a Spigot replacement, we use the older version, but PEx has been updated for spigot's newer version.

Did downgrading fix your problem?

**Comment by DefinitlyEvil** [comment]
Yes, I guess. Thanks a lot! :)
