### ISSUE TITLE
No codec to write: LoginSuccessMessage in PLAY

### ISSUE THREAD

**Issue by Chunkr-** [GlowstoneMC/Glowstone-Legacy#91]
I've been testing GlowStone on one of my Servers, it seems it's most likely to crash when a large population of players 'floods' the server.

```
Glowstone version: 1.7.2-131-g1b9431c-dev
Bukkit version:    1.7.2-R0.3
Minecraft version: 1.7.2 protocol 4
```

The server is running behind a Bungeecord Proxy, and has more than enough ram/cpu.

```
21:38:33 [WARNING] No codec to write: LoginSuccessMessage in PLAY
21:38:33 [SEVERE] Error in network output
io.netty.handler.codec.EncoderException: java.lang.Exception: Unknown message type: class net.glowstone.net.message.login.LoginSuccessMessage.
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
        at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:645)
        at io.netty.channel.DefaultChannelHandlerContext.access$2000(DefaultChannelHandlerContext.java:29)
        at io.netty.channel.DefaultChannelHandlerContext$WriteTask.run(DefaultChannelHandlerContext.java:906)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.Exception: Unknown message type: class net.glowstone.net.message.login.LoginSuccessMessage.
        at com.flowpowered.networking.pipeline.MessageEncoder.encode(MessageEncoder.java:54)
        at com.flowpowered.networking.pipeline.MessageEncoder.encode(MessageEncoder.java:41)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
        ... 7 more
```

**Comment by SpaceManiac** [comment]
Thanks for using Glowstone!
I have a change which I think will help, to net.glowstone.net.GlowSession:

``` java
    public void setProtocol(GlowProtocol protocol) {
        getChannel().flush();
        super.setProtocol(protocol);
    }
```

You can make this change yourself, or I uploaded a jar [here](http://wombat.platymuus.com/dl/glowstone-flush-fix.jar).

Try it out and let me know if this fixes it for you.

**Comment by Chunkr-** [comment]
Will try this one out tomorrow! Thanks :)

**Comment by kitskub** [comment]
@SpaceManiac I'm going to incorporate this straight into flow-networking.

Edit: actually, can you confirm with me that this does indeed fix the problem first?

**Comment by SpaceManiac** [comment]
@kitskub Actual testing has revealed that this does not appear to actually fix the problem - I'm still seeing it happen. Any ideas?

And while I've got your attention: https://gist.github.com/SpaceManiac/c4f5d55db3f5d3e11791

**Comment by SpaceManiac** [comment]
The 1.8 update which revamped the Netty pipeline appears to have finally truly fixed this.
